# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 05:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=10000)),
                ('submission_date', models.DateTimeField(auto_now=True, verbose_name='date submitted')),
                ('company', models.CharField(max_length=30)),
                ('reviewer_name', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('new', models.CharField(max_length=1)),
            ],
        ),
    ]
