# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='new',
        ),
    ]
