# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='submission_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date submitted'),
        ),
    ]
