# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='ating',
        ),
    ]
