# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20171111_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ip_addss',
            new_name='ip_address',
        ),
    ]
