# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20171111_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratin',
            new_name='rating',
        ),
    ]
