# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20171111_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', protocol='IPv4'),
        ),
    ]
