# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20171111_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_name',
            new_name='reviewer_nam',
        ),
    ]
